#!/bin/bash
# Script hướng dẫn download và setup Godot

echo "=== HƯỚNG DẪN CÀI ĐẶT GODOT ENGINE ==="
echo ""
echo "🔽 BƯỚC 1: DOWNLOAD GODOT"
echo "Windows:"
echo "  1. Mở https://godotengine.org/download"
echo "  2. Chọn 'Godot Engine 4.2.x - Standard'"
echo "  3. Click nút Download cho Windows (64-bit)"
echo ""
echo "Linux:"
echo "  wget https://github.com/godotengine/godot/releases/download/4.2.2-stable/Godot_v4.2.2-stable_linux.x86_64.zip"
echo "  unzip Godot_v4.2.2-stable_linux.x86_64.zip"
echo ""
echo "macOS:"
echo "  1. Mở https://godotengine.org/download"
echo "  2. Chọn macOS Universal"
echo "  3. Giải nén file .zip"
echo ""
echo "🚀 BƯỚC 2: CHẠY GODOT"
echo "Windows: Double-click file Godot_v4.2.x_win64.exe"
echo "Linux: ./Godot_v4.2.x_linux.x86_64"
echo "macOS: Mở Godot từ Applications"
echo ""
echo "📂 BƯỚC 3: MỞ PROJECT"
echo "1. Trong Godot Project Manager, click 'Import'"
echo "2. Chọn file 'project.godot' trong thư mục farnery/"
echo "3. Click 'Import & Edit'"
echo ""
echo "▶️ BƯỚC 4: CHẠY GAME"
echo "1. Trong Godot Editor, nhấn F5 hoặc click nút Play (▶️) ở góc trên phải"
echo "2. Chờ game compile lần đầu (có thể mất 30s-1 phút)"
echo "3. Enjoy! 🎮"
echo ""
echo "❓ GỠ LỖI:"
echo "- Nếu thiếu scenes/main.tscn: Check lại file có tồn tại"
echo "- Nếu lỗi script: Project > Reload Current Project"
echo "- Nếu lỗi parsing: Check Godot version >= 4.2"
